// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: "AIzaSyDeDQFvaLVNyNb3Gb9t0bUUmRGSH8Vz4Mw",
        authDomain: "accel-o-rot.firebaseapp.com",
        projectId: "accel-o-rot",
        storageBucket: "accel-o-rot.firebasestorage.app",
        messagingSenderId: "1087290987134",
        appId: "1:1087290987134:web:...", // ⚠️ Replace "..." with your actual web App ID
        measurementId: "G-XXXXXXXXXX", // ⚠️ Replace with your actual Measurement ID if using GA4
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDQFvaLVNyNb3Gb9t0bUUmRGSH8Vz4Mw',
    appId: '1:1087290987134:android:22cb858301dd20c5bebe2f',
    messagingSenderId: '1087290987134',
    projectId: 'accel-o-rot',
    storageBucket: 'accel-o-rot.firebasestorage.app',
  );

}