// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_application_1/test/repository/pending_member_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_application_1/data/models/user.dart' as _i3;
import 'package:flutter_application_1/data/repositories/user_repository.dart'
    as _i6;
import 'package:flutter_application_1/data/services/contracts/pagination_result.dart'
    as _i2;
import 'package:flutter_application_1/data/services/contracts/pending_member_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginationResult_0<T> extends _i1.SmartFake
    implements _i2.PaginationResult<T> {
  _FakePaginationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PendingMemberService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPendingMemberService extends _i1.Mock
    implements _i4.PendingMemberService {
  MockPendingMemberService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>?> fetchRawPendingMemberData(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRawPendingMemberData, [id]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<_i2.PaginationResult<Map<String, dynamic>>>
  fetchRawPendingMembers({
    required String? teamId,
    required int? limit,
    String? startCursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRawPendingMembers, [], {
              #teamId: teamId,
              #limit: limit,
              #startCursor: startCursor,
            }),
            returnValue:
                _i5.Future<_i2.PaginationResult<Map<String, dynamic>>>.value(
                  _FakePaginationResult_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#fetchRawPendingMembers, [], {
                      #teamId: teamId,
                      #limit: limit,
                      #startCursor: startCursor,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.PaginationResult<Map<String, dynamic>>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i6.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.User> getUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [id]),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_1(this, Invocation.method(#getUser, [id])),
            ),
          )
          as _i5.Future<_i3.User>);
}
